/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dog.glb -t -o dog.tsx 
Author: toro ardido modelos 3d (https://sketchfab.com/juansefolgueira)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dog-31f45516a1094d8fbaeec9b1efa168f1
Title: Dog
*/

import * as THREE from "three";
import React, { JSX, useEffect, useRef } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

type ActionName = "standing" | "sitting" | "shake" | "rollover" | "play_dead";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_130: THREE.SkinnedMesh;
    GLTF_created_0_rootJoint: THREE.Bone;
  };
  materials: {
    material_0: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Dog(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/dog-new.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const texture = useTexture("/base_map.png");
  texture.flipY = false;
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  materials.material_0.map = texture;
  materials.material_0.needsUpdate = true;

  useEffect(() => {
    if (actions.sitting) {
      actions.sitting.reset().fadeIn(0.5).play();
    }
  }, [actions]);
  return (
    
      <group
        scale={0.7}
        position={[-0.15, -0.9, 2.75]}
        ref={group}
        {...props}
        dispose={null}
      >
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group name="RootNode0_0" scale={0.01}>
                  <group name="skeletal3_3">
                    <group name="GLTF_created_0">
                      <primitive object={nodes.GLTF_created_0_rootJoint} />
                      <group name="shiba_inu2_2_correction">
                        <group name="shiba_inu2_2" />
                      </group>
                      <skinnedMesh
                        name="Object_130"
                        geometry={nodes.Object_130.geometry}
                        material={materials.material_0}
                        skeleton={nodes.Object_130.skeleton}
                      ></skinnedMesh>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
  );
}

useGLTF.preload("/dog.glb");
