/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 simple_flower_loop.glb -t -o flower.tsx 
Author: alexandra.m.neville (https://sketchfab.com/alexandra.m.neville)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-flower-loop-a9d02b903a494b60906d44d0c855f7a3
Title: Simple Flower Loop
*/

import * as THREE from "three";
import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName = "Object_0";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    timeshift4: THREE.Mesh;
  };
  materials: {
    timeshift4: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};

export function Flower(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/simple_flower_loop.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions.Object_0) {
      const a = actions.Object_0;
      a.timeScale = 0.05;
      a.reset().fadeIn(0.5).play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[-0.011, 0.036, 0.044]}
          rotation={[-0.039, 0.372, -1.557]}
          scale={2.0}
        >
          <group name="d9519426e61142ddacee8e1492ac5ef6abccleanermaterialmergergles">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="MorphMainGroup">
                  <mesh
                    name="timeshift4"
                    geometry={nodes.timeshift4.geometry}
                    material={materials.timeshift4}
                    morphTargetDictionary={
                      nodes.timeshift4.morphTargetDictionary
                    }
                    morphTargetInfluences={
                      nodes.timeshift4.morphTargetInfluences
                    }
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/simple_flower_loop.glb");
