/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command:  npx gltfjsx@6.5.3 cyber_spore.glb -t -o jellyfish.tsx
Author:   Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License:  CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source:   https://sketchfab.com/3d-models/cyber-spore-b811b00a737247ea9328326a05403ef0
Title:    Cyber Spore
*/

import * as THREE from 'three'
import React, { JSX, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Animation'
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;   Object_6: THREE.Mesh;   Object_8: THREE.Mesh
    Object_10: THREE.Mesh;  Object_12: THREE.Mesh;  Object_14: THREE.Mesh
    Object_16: THREE.Mesh;  Object_18: THREE.Mesh;  Object_20: THREE.Mesh
    Object_22: THREE.Mesh;  Object_24: THREE.Mesh;  Object_26: THREE.Mesh
    Object_28: THREE.Mesh;  Object_30: THREE.Mesh;  Object_32: THREE.Mesh
    Object_34: THREE.Mesh;  Object_36: THREE.Mesh;  Object_38: THREE.Mesh
    Object_40: THREE.Mesh;  Object_42: THREE.Mesh;  Object_44: THREE.Mesh
    Object_46: THREE.Mesh;  Object_48: THREE.Mesh;  Object_50: THREE.Mesh
    Object_52: THREE.Mesh;  Object_54: THREE.Mesh;  Object_56: THREE.Mesh
    Object_58: THREE.Mesh;  Object_60: THREE.Mesh;  Object_62: THREE.Mesh
    Object_64: THREE.Mesh;  Object_66: THREE.Mesh;  Object_68: THREE.Mesh
    Object_70: THREE.Mesh;  Object_72: THREE.Mesh;  Object_74: THREE.Mesh
    Object_76: THREE.Mesh;  Object_78: THREE.Mesh;  Object_80: THREE.Mesh
    Object_82: THREE.Mesh;  Object_84: THREE.Mesh;  Object_86: THREE.Mesh
    Object_88: THREE.Mesh;  Object_90: THREE.Mesh;  Object_92: THREE.Mesh
    Object_94: THREE.Mesh;  Object_96: THREE.Mesh;  Object_98: THREE.Mesh
    Object_100: THREE.Mesh; Object_102: THREE.Mesh; Object_104: THREE.Mesh
    Object_106: THREE.Mesh; Object_108: THREE.Mesh; Object_110: THREE.Mesh
    Object_112: THREE.Mesh; Object_114: THREE.Mesh; Object_116: THREE.Mesh
    Object_118: THREE.Mesh; Object_120: THREE.Mesh; Object_122: THREE.Mesh
    Object_124: THREE.Mesh; Object_126: THREE.Mesh; Object_128: THREE.Mesh
    Object_130: THREE.Mesh; Object_132: THREE.Mesh; Object_134: THREE.Mesh
    Object_136: THREE.Mesh; Object_138: THREE.Mesh; Object_140: THREE.Mesh
    Object_142: THREE.Mesh; Object_144: THREE.Mesh; Object_146: THREE.Mesh
    Object_148: THREE.Mesh; Object_150: THREE.Mesh; Object_152: THREE.Mesh
    Object_154: THREE.Mesh; Object_156: THREE.Mesh; Object_158: THREE.Mesh
    Object_160: THREE.Mesh; Object_162: THREE.Mesh; Object_164: THREE.Mesh
    Object_166: THREE.Mesh; Object_168: THREE.Mesh; Object_170: THREE.Mesh
    Object_172: THREE.Mesh; Object_174: THREE.Mesh; Object_176: THREE.Mesh
    Object_178: THREE.Mesh; Object_180: THREE.Mesh; Object_182: THREE.Mesh
    Object_184: THREE.Mesh; Object_186: THREE.Mesh; Object_188: THREE.Mesh
    Object_190: THREE.Mesh; Object_192: THREE.Mesh; Object_194: THREE.Mesh
    Object_196: THREE.Mesh; Object_198: THREE.Mesh; Object_200: THREE.Mesh
    Object_202: THREE.Mesh; Object_204: THREE.Mesh; Object_206: THREE.Mesh
    Object_208: THREE.Mesh; Object_210: THREE.Mesh; Object_212: THREE.Mesh
    Object_214: THREE.Mesh; Object_216: THREE.Mesh; Object_218: THREE.Mesh
    Object_220: THREE.Mesh; Object_222: THREE.Mesh; Object_224: THREE.Mesh
    Object_226: THREE.Mesh; Object_228: THREE.Mesh; Object_230: THREE.Mesh
    Object_232: THREE.Mesh; Object_234: THREE.Mesh; Object_236: THREE.Mesh
    Object_238: THREE.Mesh; Object_240: THREE.Mesh; Object_242: THREE.Mesh
    Object_244: THREE.Mesh; Object_246: THREE.Mesh; Object_248: THREE.Mesh
    Object_250: THREE.Mesh; Object_252: THREE.Mesh; Object_254: THREE.Mesh
    Object_256: THREE.Mesh; Object_258: THREE.Mesh; Object_260: THREE.Mesh
    Object_262: THREE.Mesh; Object_264: THREE.Mesh; Object_266: THREE.Mesh
    Object_268: THREE.Mesh; Object_270: THREE.Mesh; Object_272: THREE.Mesh
    Object_274: THREE.Mesh; Object_276: THREE.Mesh; Object_278: THREE.Mesh
    Object_280: THREE.Mesh; Object_282: THREE.Mesh; Object_284: THREE.Mesh
    Object_286: THREE.Mesh; Object_288: THREE.Mesh; Object_290: THREE.Mesh
    Object_292: THREE.Mesh; Object_294: THREE.Mesh; Object_296: THREE.Mesh
    Object_298: THREE.Mesh; Object_300: THREE.Mesh; Object_302: THREE.Mesh
  }
  materials: { ['Scene_-_Root']: THREE.MeshStandardMaterial }
  animations: GLTFAction[]
}

export function Jellyfish(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/cyber_spore.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  /* ------------ colour palette ------------ */
  const warm = ['#ffb347', '#ff9234', '#ff7300', '#ff5400'] // oranges
  const cool = ['#00b4d8', '#0096c7', '#0077b6', '#023e8a'] // blues
  /* ---------------------------------------- */

  useEffect(() => {
    /* play baked animation in slo-mo */
    if (actions.Animation) {
      const a = actions.Animation
      a.timeScale = 0.05
      a.reset().fadeIn(0.5).play()
    }

    /* give every mesh its own clean material */
    const meshes: THREE.Mesh[] = []
    group.current.traverse(o => {
      if ((o as THREE.Mesh).isMesh) meshes.push(o as THREE.Mesh)
    })

    const base = materials['Scene_-_Root'] as THREE.MeshStandardMaterial

    meshes.forEach((mesh, idx) => {
      const mat = base.clone()
      /* strip everything that carries baked colours */
      mat.map = null
      mat.emissiveMap = null
      mat.vertexColors = false

      /* choose palette & shade */
      const palette = idx % 2 === 0 ? warm : cool
      const shade   = palette[(idx >> 1) % palette.length]

      /* set tint + subtle emissive glow */
      mat.color.set(shade)
      mat.emissive.set(shade).multiplyScalar(0.25)
      mat.needsUpdate = true

      mesh.material = mat
    })
  }, [actions, materials])

  /* ---------------  full hierarchy (unchanged) --------------- */
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" scale={1.7}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              {/* ring 1 (scale 0.686) */}
              <group name="Torus027_0" scale={0.686}>
                <mesh geometry={nodes.Object_4.geometry}   material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus028_1" scale={0.686}>
                <mesh geometry={nodes.Object_6.geometry}   material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus029_2" scale={0.686}>
                <mesh geometry={nodes.Object_8.geometry}   material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus030_3" scale={0.686}>
                <mesh geometry={nodes.Object_10.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus031_4" scale={0.686}>
                <mesh geometry={nodes.Object_12.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus032_5" scale={0.686}>
                <mesh geometry={nodes.Object_14.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus033_6" scale={0.686}>
                <mesh geometry={nodes.Object_16.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus034_7" scale={0.686}>
                <mesh geometry={nodes.Object_18.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus035_8" scale={0.686}>
                <mesh geometry={nodes.Object_20.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus036_9" scale={0.686}>
                <mesh geometry={nodes.Object_22.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus037_10" scale={0.686}>
                <mesh geometry={nodes.Object_24.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus038_11" scale={0.686}>
                <mesh geometry={nodes.Object_26.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus039_12" scale={0.686}>
                <mesh geometry={nodes.Object_28.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus040_13" scale={0.686}>
                <mesh geometry={nodes.Object_30.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus041_14" scale={0.686}>
                <mesh geometry={nodes.Object_32.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus042_15" scale={0.686}>
                <mesh geometry={nodes.Object_34.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus043_16" scale={0.686}>
                <mesh geometry={nodes.Object_36.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus044_17" scale={0.686}>
                <mesh geometry={nodes.Object_38.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus045_18" scale={0.686}>
                <mesh geometry={nodes.Object_40.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus046_19" scale={0.686}>
                <mesh geometry={nodes.Object_42.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus047_20" scale={0.686}>
                <mesh geometry={nodes.Object_44.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus048_21" scale={0.686}>
                <mesh geometry={nodes.Object_46.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus049_22" scale={0.686}>
                <mesh geometry={nodes.Object_48.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus050_23" scale={0.686}>
                <mesh geometry={nodes.Object_50.geometry}  material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus051_24" scale={0.686}>
                <mesh geometry={nodes.Object_52.geometry}  material={materials['Scene_-_Root']} />
              </group>

              {/* ring 2 (scale 0.854) */}
              <group name="Torus001_25" scale={0.854}>
                <mesh geometry={nodes.Object_54.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus002_26" scale={0.854}>
                <mesh geometry={nodes.Object_56.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus003_27" scale={0.854}>
                <mesh geometry={nodes.Object_58.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus004_28" scale={0.854}>
                <mesh geometry={nodes.Object_60.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus005_29" scale={0.854}>
                <mesh geometry={nodes.Object_62.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus006_30" scale={0.854}>
                <mesh geometry={nodes.Object_64.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus007_31" scale={0.854}>
                <mesh geometry={nodes.Object_66.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus008_32" scale={0.854}>
                <mesh geometry={nodes.Object_68.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus009_33" scale={0.854}>
                <mesh geometry={nodes.Object_70.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus010_34" scale={0.854}>
                <mesh geometry={nodes.Object_72.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus011_35" scale={0.854}>
                <mesh geometry={nodes.Object_74.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus012_36" scale={0.854}>
                <mesh geometry={nodes.Object_76.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus013_37" scale={0.854}>
                <mesh geometry={nodes.Object_78.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus014_38" scale={0.854}>
                <mesh geometry={nodes.Object_80.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus015_39" scale={0.854}>
                <mesh geometry={nodes.Object_82.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus016_40" scale={0.854}>
                <mesh geometry={nodes.Object_84.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus017_41" scale={0.854}>
                <mesh geometry={nodes.Object_86.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus018_42" scale={0.854}>
                <mesh geometry={nodes.Object_88.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus019_43" scale={0.854}>
                <mesh geometry={nodes.Object_90.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus020_44" scale={0.854}>
                <mesh geometry={nodes.Object_92.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus021_45" scale={0.854}>
                <mesh geometry={nodes.Object_94.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus022_46" scale={0.854}>
                <mesh geometry={nodes.Object_96.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus023_47" scale={0.854}>
                <mesh geometry={nodes.Object_98.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus024_48" scale={0.854}>
                <mesh geometry={nodes.Object_100.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus025_49" scale={0.854}>
                <mesh geometry={nodes.Object_102.geometry} material={materials['Scene_-_Root']} />
              </group>

              {/* ring 3 (scale 0.425) */}
              <group name="Torus026_103" scale={0.425}>
                <mesh geometry={nodes.Object_104.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus052_104" scale={0.425}>
                <mesh geometry={nodes.Object_106.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus053_105" scale={0.425}>
                <mesh geometry={nodes.Object_108.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus054_106" scale={0.425}>
                <mesh geometry={nodes.Object_110.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus055_107" scale={0.425}>
                <mesh geometry={nodes.Object_112.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus056_108" scale={0.425}>
                <mesh geometry={nodes.Object_114.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus057_109" scale={0.425}>
                <mesh geometry={nodes.Object_116.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus058_110" scale={0.425}>
                <mesh geometry={nodes.Object_118.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus059_111" scale={0.425}>
                <mesh geometry={nodes.Object_120.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus060_112" scale={0.425}>
                <mesh geometry={nodes.Object_122.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus061_113" scale={0.425}>
                <mesh geometry={nodes.Object_124.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus062_114" scale={0.425}>
                <mesh geometry={nodes.Object_126.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus063_115" scale={0.425}>
                <mesh geometry={nodes.Object_128.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus064_116" scale={0.425}>
                <mesh geometry={nodes.Object_130.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus065_117" scale={0.425}>
                <mesh geometry={nodes.Object_132.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus066_118" scale={0.425}>
                <mesh geometry={nodes.Object_134.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus067_119" scale={0.425}>
                <mesh geometry={nodes.Object_136.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus068_120" scale={0.425}>
                <mesh geometry={nodes.Object_138.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus069_121" scale={0.425}>
                <mesh geometry={nodes.Object_140.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus070_122" scale={0.425}>
                <mesh geometry={nodes.Object_142.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus071_123" scale={0.425}>
                <mesh geometry={nodes.Object_144.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus072_124" scale={0.425}>
                <mesh geometry={nodes.Object_146.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus073_125" scale={0.425}>
                <mesh geometry={nodes.Object_148.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus074_126" scale={0.425}>
                <mesh geometry={nodes.Object_150.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus075_127" scale={0.425}>
                <mesh geometry={nodes.Object_152.geometry} material={materials['Scene_-_Root']} />
              </group>

              {/* ring 4 (scale 0.529) */}
              <group name="Torus076_128" scale={0.529}>
                <mesh geometry={nodes.Object_154.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus077_129" scale={0.529}>
                <mesh geometry={nodes.Object_156.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus078_130" scale={0.529}>
                <mesh geometry={nodes.Object_158.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus079_131" scale={0.529}>
                <mesh geometry={nodes.Object_160.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus080_132" scale={0.529}>
                <mesh geometry={nodes.Object_162.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus081_133" scale={0.529}>
                <mesh geometry={nodes.Object_164.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus082_134" scale={0.529}>
                <mesh geometry={nodes.Object_166.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus083_135" scale={0.529}>
                <mesh geometry={nodes.Object_168.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus084_136" scale={0.529}>
                <mesh geometry={nodes.Object_170.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus085_137" scale={0.529}>
                <mesh geometry={nodes.Object_172.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus086_138" scale={0.529}>
                <mesh geometry={nodes.Object_174.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus087_139" scale={0.529}>
                <mesh geometry={nodes.Object_176.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus088_140" scale={0.529}>
                <mesh geometry={nodes.Object_178.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus089_141" scale={0.529}>
                <mesh geometry={nodes.Object_180.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus090_142" scale={0.529}>
                <mesh geometry={nodes.Object_182.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus091_143" scale={0.529}>
                <mesh geometry={nodes.Object_184.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus092_144" scale={0.529}>
                <mesh geometry={nodes.Object_186.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus093_145" scale={0.529}>
                <mesh geometry={nodes.Object_188.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus094_146" scale={0.529}>
                <mesh geometry={nodes.Object_190.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus095_147" scale={0.529}>
                <mesh geometry={nodes.Object_192.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus096_148" scale={0.529}>
                <mesh geometry={nodes.Object_194.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus097_149" scale={0.529}>
                <mesh geometry={nodes.Object_196.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus098_150" scale={0.529}>
                <mesh geometry={nodes.Object_198.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus099_151" scale={0.529}>
                <mesh geometry={nodes.Object_200.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus100_152" scale={0.529}>
                <mesh geometry={nodes.Object_202.geometry} material={materials['Scene_-_Root']} />
              </group>

              {/* ring 5 (scale 0.258) */}
              <group name="Torus101_206" scale={0.258}>
                <mesh geometry={nodes.Object_204.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus102_207" scale={0.258}>
                <mesh geometry={nodes.Object_206.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus103_208" scale={0.258}>
                <mesh geometry={nodes.Object_208.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus104_209" scale={0.258}>
                <mesh geometry={nodes.Object_210.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus105_210" scale={0.258}>
                <mesh geometry={nodes.Object_212.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus106_211" scale={0.258}>
                <mesh geometry={nodes.Object_214.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus107_212" scale={0.258}>
                <mesh geometry={nodes.Object_216.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus108_213" scale={0.258}>
                <mesh geometry={nodes.Object_218.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus109_214" scale={0.258}>
                <mesh geometry={nodes.Object_220.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus110_215" scale={0.258}>
                <mesh geometry={nodes.Object_222.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus111_216" scale={0.258}>
                <mesh geometry={nodes.Object_224.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus112_217" scale={0.258}>
                <mesh geometry={nodes.Object_226.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus113_218" scale={0.258}>
                <mesh geometry={nodes.Object_228.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus114_219" scale={0.258}>
                <mesh geometry={nodes.Object_230.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus115_220" scale={0.258}>
                <mesh geometry={nodes.Object_232.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus116_221" scale={0.258}>
                <mesh geometry={nodes.Object_234.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus117_222" scale={0.258}>
                <mesh geometry={nodes.Object_236.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus118_223" scale={0.258}>
                <mesh geometry={nodes.Object_238.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus119_224" scale={0.258}>
                <mesh geometry={nodes.Object_240.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus120_225" scale={0.258}>
                <mesh geometry={nodes.Object_242.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus121_226" scale={0.258}>
                <mesh geometry={nodes.Object_244.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus122_227" scale={0.258}>
                <mesh geometry={nodes.Object_246.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus123_228" scale={0.258}>
                <mesh geometry={nodes.Object_248.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus124_229" scale={0.258}>
                <mesh geometry={nodes.Object_250.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus125_230" scale={0.258}>
                <mesh geometry={nodes.Object_252.geometry} material={materials['Scene_-_Root']} />
              </group>

              {/* ring 6 (scale 0.321) */}
              <group name="Torus126_231" scale={0.321}>
                <mesh geometry={nodes.Object_254.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus127_232" scale={0.321}>
                <mesh geometry={nodes.Object_256.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus128_233" scale={0.321}>
                <mesh geometry={nodes.Object_258.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus129_234" scale={0.321}>
                <mesh geometry={nodes.Object_260.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus130_235" scale={0.321}>
                <mesh geometry={nodes.Object_262.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus131_236" scale={0.321}>
                <mesh geometry={nodes.Object_264.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus132_237" scale={0.321}>
                <mesh geometry={nodes.Object_266.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus133_238" scale={0.321}>
                <mesh geometry={nodes.Object_268.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus134_239" scale={0.321}>
                <mesh geometry={nodes.Object_270.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus135_240" scale={0.321}>
                <mesh geometry={nodes.Object_272.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus136_241" scale={0.321}>
                <mesh geometry={nodes.Object_274.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus137_242" scale={0.321}>
                <mesh geometry={nodes.Object_276.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus138_243" scale={0.321}>
                <mesh geometry={nodes.Object_278.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus139_244" scale={0.321}>
                <mesh geometry={nodes.Object_280.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus140_245" scale={0.321}>
                <mesh geometry={nodes.Object_282.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus141_246" scale={0.321}>
                <mesh geometry={nodes.Object_284.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus142_247" scale={0.321}>
                <mesh geometry={nodes.Object_286.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus143_248" scale={0.321}>
                <mesh geometry={nodes.Object_288.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus144_249" scale={0.321}>
                <mesh geometry={nodes.Object_290.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus145_250" scale={0.321}>
                <mesh geometry={nodes.Object_292.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus146_251" scale={0.321}>
                <mesh geometry={nodes.Object_294.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus147_252" scale={0.321}>
                <mesh geometry={nodes.Object_296.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus148_253" scale={0.321}>
                <mesh geometry={nodes.Object_298.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus149_254" scale={0.321}>
                <mesh geometry={nodes.Object_300.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Torus150_255" scale={0.321}>
                <mesh geometry={nodes.Object_302.geometry} material={materials['Scene_-_Root']} />
              </group>

              {/* centre disc */}
              <group name="Circle159_309" scale={14.473} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cyber_spore.glb')
